version: '3'
services:
  domet-io-nginx:
    image: nginx:latest
    ports:
      - "8903:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./:/docker
  domet-io-phpfpm:
    image: 'php:fpm-alpine3.16'
    volumes:
      - ./:/docker