version: '3'
services:
  domet-io-nginx:
    image: nginx:latest
    ports:
      - "8903:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./:/docker
  domet-io-phpfpm:
    image: 'php:fpm-alpine3.16'
    volumes:
      - ./:/docker
  domet-io-mariadb:
    image: mariadb:10.9.3
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf